// ============================================================================
// SANMAR SERVER LOADER - Strictly for Server-Side Data Loading (FS/Path)
// ============================================================================
import 'server-only';

import { Product } from '@/types/products';
import { std_getProductInfoByStyleColorSize } from './sanmar';
import { parseSanMarXmlResponse, sanMarProductToProduct } from './sanmar-parser';
import { getAllStyleCodes } from './sanmar-products';
import fs from 'fs';
import path from 'path';

/**
 * Fetch a single product (Real-time availability check or Fallback)
 * 1. Checks Static JSON
 * 2. Falls back to API
 */
export async function fetchSanMarProductByStyle(style: string): Promise<Product[]> {
    try {
        // 1. Try Cache
        const filePath = path.join(process.cwd(), 'src', 'data', 'products-catalog.json');
        if (fs.existsSync(filePath)) {
            const fileContent = await fs.promises.readFile(filePath, 'utf-8');
            const catalog = JSON.parse(fileContent) as Product[];
            const cached = catalog.find(p => p.slug === style.toLowerCase() || p.slug === style);
            if (cached) return [cached];
        }

        // 2. API Fallback (Real-Time)
        const xmlResponse = await std_getProductInfoByStyleColorSize({
            style: style.trim(),
        });

        const parsedProducts = parseSanMarXmlResponse(xmlResponse);
        if (!parsedProducts.length) return [];

        return sanMarProductToProduct(parsedProducts);
    } catch (error) {
        console.warn(`Error fetching style ${style}:`, error);
        return [];
    }
}

/**
 * Fetch multiple products by style codes
 */
export async function fetchSanMarProductsByStyles(styles: string[]): Promise<Product[]> {
    const fetchPromises = styles.map(style => fetchSanMarProductByStyle(style));
    const results = await Promise.allSettled(fetchPromises);

    const products: Product[] = [];

    for (const result of results) {
        if (result.status === 'fulfilled') {
            products.push(...result.value);
        }
    }

    return products;
}

/**
 * Fetch ALL SanMar products (Used by /products page)
 * Prioritizes Static JSON Catalog
 */
export async function fetchAllSanMarProducts(): Promise<Product[]> {
    try {
        // Try to load from static catalog (generated by script)
        const filePath = path.join(process.cwd(), 'src', 'data', 'products-catalog.json');

        if (fs.existsSync(filePath)) {
            const fileContent = await fs.promises.readFile(filePath, 'utf-8');
            const products = JSON.parse(fileContent) as Product[];
            return products;
        } else {
            console.warn('Static catalog not found. Falling back to manual list API fetch (Slow).');
        }
    } catch (e) {
        console.error('Error reading static catalog:', e);
    }

    // Fallback to manual list via API (Slow, legacy behavior)
    const styleCodes = getAllStyleCodes();
    return fetchSanMarProductsByStyles(styleCodes);
}

/**
 * Fetch products by category slug (Legacy helper)
 */
export async function fetchSanMarProductsByCategory(
    categorySlug: 'workwear' | 'activewear' | 'woven-shirts' | 'personal-protection'
): Promise<Product[]> {
    // Ideally this should filter the JSON too, but for legacy compatibility we keep logic or use getAll+Filter
    const all = await fetchAllSanMarProducts();
    // Filter locally
    // Warning: This mapping might be loose
    return all.filter(p => (p.tags && p.tags.includes(categorySlug)) || (p.category && p.category.slug === categorySlug));
}

export interface ProductFetchProgress {
    total: number;
    loaded: number;
    products: Product[];
}

export async function fetchSanMarProductsWithProgress(
    styles: string[],
    batchSize: number = 5,
    onProgress?: (progress: ProductFetchProgress) => void
): Promise<Product[]> {
    const all = await fetchSanMarProductsByStyles(styles);
    if (onProgress) onProgress({ total: styles.length, loaded: styles.length, products: all });
    return all;
}
